application: styleshot-otchy-net
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /app
  static_dir: app
- url: /core/css
  static_dir: core/css
- url: /core/js
  static_dir: core/js
- url: /core/fonts
  static_dir: core/fonts
- url: /([^/]+)\.(js|css|gif|jpg|png)$
  static_files: \1.\2
  upload: ([^/]+)\.(js|css|gif|jpg|png)$
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest